// content/education.ts
import type { Education } from '@/lib/types';

const education: Education[] = [
  {
    id: 'edu-1',
    title: 'Universitas Maritim Raja Ali Haji',
    school: 'Universitas Maritim Raja Ali Haji',
    degree: 'S1 Informatika',
    category: 'formal',
    description: 'Fokus pada backend engineering, database optimasi, dan kecerdasan buatan. Aktif di organisasi kemahasiswaan dan kompetisi.',
    startDate: '2025-01-01',
    endDate: null,
    featured: true,
    tags: ['Backend', 'Database', 'AI'],
    gpa: '3.9',
    location: 'Kota Tanjung Pinang, Kepulauan Riau',
    logo: '/images/logos/umrah.png',
    link: 'https://umrah.ac.id',
  },
  {
    id: 'edu-2',
    title: 'SMA Tunas Bangsa Bintan',
    school: 'SMA Tunas Bangsa Bintan',
    degree: 'Mapel Pilihan: Matematika Lanjut, Biologi, Kimia, Fisika, PKWU',
    category: 'formal',
    description: 'Lulus dengan predikat memuaskan, aktif di organisasi dan kegiatan ekstrakurikuler. Mengambil mapel wajib (Matematika, PKN, Sejarah, PJOK, Bahasa Inggris, Seni Budaya) serta mapel pilihan sesuai minat di bidang sains dan teknologi.',
    startDate: '2022-01-01',
    endDate: '2025-01-01',
    featured: false,
    tags: ['Matematika Lanjut', 'Biologi', 'Kimia', 'Fisika', 'PKWU'],
    location: 'Bintan, Kepulauan Riau',
    logo: '/images/logos/sma-tunas-bangsa.png',
  },
  {
    id: 'edu-3',
    title: 'SMP Islam Terpadu Bahtera Insani',
    school: 'SMP Islam Terpadu Bahtera Insani',
    degree: 'SMP',
    category: 'formal',
    description: 'Menempuh pendidikan menengah pertama dengan prestasi akademik yang baik.',
    startDate: '2019-01-01',
    endDate: '2022-01-01',
    featured: false,
    tags: ['SMP'],
    location: 'Bintan, Kepulauan Riau',
    logo: '/images/logos/smp-it-bahtera-insani.png',
  },
  {
    id: 'edu-4',
    title: 'SD Negeri 001 Bintan Utara',
    school: 'SD Negeri 001 Bintan Utara',
    degree: 'SD',
    category: 'formal',
    description: 'Pendidikan dasar yang menjadi fondasi awal perjalanan akademik.',
    startDate: '2013-01-01',
    endDate: '2019-01-01',
    featured: false,
    tags: ['SD'],
    location: 'Bintan, Kepulauan Riau',
    logo: '/images/logos/sdn-001-bintan-utara.png',
  },
];

export default education;